export const STATE_BORDERS: { [key: string]: string[] } = {
  AL: ["MS", "TN", "GA", "FL"],
  AK: [],
  AZ: ["CA", "NV", "UT", "CO", "NM"],
  AR: ["MO", "TN", "MS", "LA", "TX", "OK"],
  CA: ["OR", "NV", "AZ"],
  CO: ["WY", "NE", "KS", "OK", "NM", "AZ", "UT"],
  CT: ["NY", "MA", "RI"],
  DE: ["MD", "PA", "NJ"],
  FL: ["AL", "GA"],
  GA: ["TN", "NC", "SC", "FL", "AL"],
  HI: [],
  ID: ["MT", "WY", "UT", "NV", "OR", "WA"],
  IL: ["WI", "IA", "MO", "KY", "IN"],
  IN: ["MI", "OH", "KY", "IL"],
  IA: ["MN", "WI", "IL", "MO", "NE", "SD"],
  KS: ["NE", "MO", "OK", "CO"],
  KY: ["IL", "IN", "OH", "WV", "VA", "TN", "MO"],
  LA: ["TX", "AR", "MS"],
  ME: ["NH"],
  MD: ["PA", "DE", "VA", "WV"],
  MA: ["NY", "VT", "NH", "RI", "CT"],
  MI: ["OH", "IN", "WI"],
  MN: ["WI", "IA", "SD", "ND"],
  MS: ["LA", "AR", "TN", "AL"],
  MO: ["IA", "IL", "KY", "TN", "AR", "OK", "KS", "NE"],
  MT: ["ND", "SD", "WY", "ID"],
  NE: ["SD", "IA", "MO", "KS", "CO", "WY"],
  NV: ["OR", "ID", "UT", "AZ", "CA"],
  NH: ["VT", "ME", "MA"],
  NJ: ["NY", "PA", "DE"],
  NM: ["AZ", "CO", "OK", "TX"],
  NY: ["PA", "NJ", "CT", "MA", "VT"],
  NC: ["VA", "TN", "GA", "SC"],
  ND: ["MT", "SD", "MN"],
  OH: ["PA", "WV", "KY", "IN", "MI"],
  OK: ["KS", "MO", "AR", "TX", "NM", "CO"],
  OR: ["WA", "ID", "NV", "CA"],
  PA: ["NY", "NJ", "DE", "MD", "WV", "OH"],
  RI: ["CT", "MA"],
  SC: ["NC", "GA"],
  SD: ["ND", "MN", "IA", "NE", "WY", "MT"],
  TN: ["KY", "VA", "NC", "GA", "AL", "MS", "AR", "MO"],
  TX: ["NM", "OK", "AR", "LA"],
  UT: ["ID", "WY", "CO", "NM", "AZ", "NV"],
  VT: ["NY", "NH", "MA"],
  VA: ["MD", "NC", "TN", "KY", "WV"],
  WA: ["ID", "OR"],
  WV: ["OH", "PA", "MD", "VA", "KY"],
  WI: ["MN", "IA", "IL", "MI"],
  WY: ["MT", "SD", "NE", "CO", "UT", "ID"]
};
